# -*- coding: utf-8 -*-
"""MyBitcoinproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-Vd7s-eZz_i3zH6fyULRlxAjjZuKAe-

Setup & Data Cleaning of my dataset
"""

import numpy as np
import pandas as pd

bitcoin= pd.read_csv('bitcoin_dataset.csv')
bitcoin.head()

bitcoin['year'] = pd.to_datetime(bitcoin['Date']).dt.year
bitcoin['month'] = pd.to_datetime(bitcoin['Date']).dt.month
bitcoin['day'] = pd.to_datetime(bitcoin['Date']).dt.day
bitcoin.head()

bitcoin.duplicated()

bitcoin.index = pd.to_datetime(bitcoin['Date'])
bitcoin.head()

bitcoin.Date.duplicated()

bitcoin_drop= bitcoin.drop(['Adj Close','Date'], axis=1)

bitcoin_drop.head()

bitcoin_drop.describe()

"""Ploting the closing price over time — this is the headline chart and tells the full Bitcoin story at a glance"""

import numpy as np
import matplotlib.pyplot as plt

X = bitcoin['Close']
Y = bitcoin['Date']

fig, ax = plt.subplots()
ax.plot(Y, X)
plt.xlabel('Date')
plt.ylabel('Close Price')
plt.title('Bitcoin Close Price Over Time')
plt.show()

"""Ploting trading volume over time — spikes in volume often coincide with big price moves"""

X = bitcoin['Volume']
Y = bitcoin['Date']

fig,ax=plt.subplots()
ax.plot(Y,X)
plt.xlabel('Date')
plt.ylabel('volume')
plt.title('Bitcoin Volume Over Time')
plt.show()

"""how much % Bitcoin moved each day"""

bitcoin_drop['daily return'] = (bitcoin_drop['Close'] - bitcoin_drop['Open'])/(bitcoin_drop['Open']*100)
bitcoin_drop.head()

"""how volatile each day was"""

bitcoin_drop['Daily Range'] = (bitcoin_drop['High']- bitcoin_drop['Low'])
bitcoin_drop.head()

"""standard in finance for compounding analysis"""

bitcoin_drop['Log Return']=np.log(bitcoin_drop['Close'] / bitcoin_drop['Close'].shift(1))
bitcoin_drop.head()

"""Bitcoin's growth per year"""

bitcoin_drop.groupby('year').sum()

"""Bitcoin's growth per Month"""

bitcoin_drop.groupby('month').mean()

"""visual annotation on major crashes (2018, 2022) and peaks (2021, 2024) on the price chart"""

plt.figure(figsize=(14, 8))
plt.plot(bitcoin.index, bitcoin['Close'], label='Bitcoin Close Price', color='skyblue')

# Annotate Crashes

# 2018 Crash: Find the minimum close price between October 2018 and January 2019
crash_2018_date = bitcoin.loc['2018-10':'2019-01', 'Close'].idxmin()
crash_2018_price = bitcoin.loc[crash_2018_date, 'Close']
plt.annotate('2018 Crash', xy=(crash_2018_date, crash_2018_price),
             xytext=(pd.to_datetime('2018-06-01'), crash_2018_price + 15000),
             arrowprops=dict(facecolor='red', shrink=0.05, width=1.5),
             horizontalalignment='center', verticalalignment='bottom', color='red', fontsize=10)

# 2022 Crash: Find the minimum close price between May and July 2022
crash_2022_date = bitcoin.loc['2022-05':'2022-07', 'Close'].idxmin()
crash_2022_price = bitcoin.loc[crash_2022_date, 'Close']
plt.annotate('2022 Crash', xy=(crash_2022_date, crash_2022_price),
             xytext=(pd.to_datetime('2021-12-01'), crash_2022_price + 25000),
             arrowprops=dict(facecolor='red', shrink=0.05, width=1.5),
             horizontalalignment='center', verticalalignment='bottom', color='red', fontsize=10)

# Annotate Peaks

# 2021 Peak: Find the maximum close price between September and December 2021
peak_2021_date = bitcoin.loc['2021-09':'2021-12', 'Close'].idxmax()
peak_2021_price = bitcoin.loc[peak_2021_date, 'Close']
plt.annotate('2021 Peak', xy=(peak_2021_date, peak_2021_price),
             xytext=(pd.to_datetime('2021-03-01'), peak_2021_price + 10000),
             arrowprops=dict(facecolor='green', shrink=0.05, width=1.5),
             horizontalalignment='center', verticalalignment='bottom', color='green', fontsize=10)

# 2024 Peak: Find the maximum close price within the year 2024 data
bitcoin_2024 = bitcoin[bitcoin.index.year == 2024]
if not bitcoin_2024.empty:
    peak_2024_date = bitcoin_2024['Close'].idxmax()
    peak_2024_price = bitcoin_2024.loc[peak_2024_date, 'Close']
    plt.annotate('2024 Peak', xy=(peak_2024_date, peak_2024_price),
                 xytext=(pd.to_datetime('2023-09-01'), peak_2024_price + 10000),
                 arrowprops=dict(facecolor='green', shrink=0.05, width=1.5),
                 horizontalalignment='center', verticalalignment='bottom', color='green', fontsize=10)
else:
    print("No data for 2024 to identify a peak.")


plt.xlabel('Date', fontsize=12)
plt.ylabel('Close Price (USD)', fontsize=12)
plt.title('Bitcoin Close Price with Major Market Events', fontsize=14)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.tight_layout()
plt.show()

""" volatility measure"""

bitcoin_drop['Rolling 30-day Daily Return'] = bitcoin_drop['daily return'].rolling(window=30).std()
bitcoin_drop.tail()

"""Rolling 7-day and 30-day moving averages of closing price


"""

bitcoin_drop['7DR'] = bitcoin_drop.Close.rolling(window=7).mean()
bitcoin_drop['30DR'] = bitcoin_drop.Close.rolling(window=30).mean()
bitcoin_drop.head()

"""Ploting Rolling 7-day and 30-day moving averages of closing price"""

plt.figure(figsize=(14, 8))
plt.plot(bitcoin_drop.index, bitcoin_drop['Close'], label='Bitcoin Close Price', color='skyblue')
plt.plot(bitcoin_drop.index, bitcoin_drop['7DR'], label='7-Day Rolling Mean', color='orange')
plt.plot(bitcoin_drop.index, bitcoin_drop['30DR'], label='30-Day Rolling Mean', color='green')

plt.xlabel('Date', fontsize=12)
plt.ylabel('Price (USD)', fontsize=12)
plt.title('Bitcoin Close Price with 7-day and 30-day Moving Averages', fontsize=14)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.tight_layout()
plt.show()

""" Top 10 most volatile days"""

bitcoin_drop.sort_values(by = 'Rolling 30-day Daily Return', ascending=True).head(10)

"""Correlation between volume and price change"""

bitcoin_drop.Volume.corr(bitcoin_drop['Open']-bitcoin_drop['Close'])

"""Average volume by year"""

avg_volume =(bitcoin_drop.groupby(bitcoin_drop.index.year)['Volume'].mean())
avg_volume

"""Ploting volume as a bar chart under the price line chart"""

# Create a figure and a set of subplots
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10), sharex=True, gridspec_kw={'height_ratios': [3, 1]})

# Plotting Price on the first subplot (ax1)
ax1.plot(bitcoin_drop.index, bitcoin_drop['Close'], label='Bitcoin Close Price', color='skyblue')
ax1.plot(bitcoin_drop.index, bitcoin_drop['7DR'], label='7-Day Rolling Mean', color='orange', linestyle='--')
ax1.plot(bitcoin_drop.index, bitcoin_drop['30DR'], label='30-Day Rolling Mean', color='green', linestyle='--')
ax1.set_ylabel('Price (USD)', fontsize=12)
ax1.set_title('Bitcoin Price and Volume Analysis', fontsize=14)
ax1.grid(True, linestyle='--', alpha=0.7)
ax1.legend()

# Plotting Volume on the second subplot (ax2)
ax2.bar(bitcoin_drop.index, bitcoin_drop['Volume'], label='Volume', color='grey', alpha=0.7)
ax2.set_xlabel('Date', fontsize=12)
ax2.set_ylabel('Volume', fontsize=12)
ax2.grid(True, linestyle='--', alpha=0.7)
ax2.legend()

plt.tight_layout()
plt.show()

Best_days = bitcoin_drop['daily return'].idxmax()
Best_days

Worse_days = bitcoin_drop['daily return'].idxmin()
Worse_days

Best_year = bitcoin_drop.groupby(bitcoin_drop.index.year)['daily return'].idxmax()
Best_year

worse_year = bitcoin_drop.groupby(bitcoin_drop.index.year)['daily return'].idxmin()
worse_year

start_price = bitcoin_drop.Close.iloc[0]
start_date =bitcoin_drop.index[0]
print(f'\nstarting pprice on {start_date.date()}: ${start_price:,.1f}\n')

for multiples in [10, 100, 200]:
  Target = start_price*multiples
  crossed = bitcoin_drop[bitcoin_drop.Close>=Target]
  if not crossed.empty:
    reached =crossed.index[0]
    days = (reached-start_date).days
    years =days/365.25 #considering the leap year
    print(f' {multiples:>3}x → Target ${Target:>10,.0f} '
          f'reached on {reached.date()}'
          f'({days:,} days/ {years:.1f}years)')
  else:
    print(f'{multiples:>3}x → Target ${Target:>10,.0f} not yet reachead in dataset')

rolling_max = bitcoin_drop['Close'].cummax()
drawdown    = (bitcoin_drop['Close'] - rolling_max) / rolling_max * 100

print("\nTop 5 Deepest Crash Points:")
for date, val in drawdown.nsmallest(5).items():
    peak   = rolling_max.loc[date]
    trough = bitcoin_drop.loc[date, 'Close']
    print(f"  {date.date()}  →  {val:.1f}%  "
          f"(peak ${peak:>10,.0f}  →  trough ${trough:>10,.0f})")

max_dd_date = drawdown.idxmin()
print(f"\n  Maximum Drawdown Ever : {drawdown.min():.1f}%  on {max_dd_date.date()}")

total_days    = len(bitcoin_drop)
positive_days = (bitcoin_drop['daily return'] > 0).sum()
negative_days = (bitcoin_drop['daily return'] < 0).sum()
overall_ret   = (bitcoin_drop['Close'].iloc[-1] - bitcoin_drop['Close'].iloc[0]) / bitcoin_drop['Close'].iloc[0] * 100
ann_vol       = bitcoin_drop['Log Return'].std() * np.sqrt(365) * 100

vol_corr = bitcoin_drop['Volume'].corr(bitcoin_drop['Open'] - bitcoin_drop['Close'])

print(f"""
  Period              : {bitcoin_drop.index[0].date()} → {bitcoin_drop.index[-1].date()}
  Total trading days  : {total_days:,}

  Starting price      : ${bitcoin_drop['Close'].iloc[0]:>12,.2f}
  Latest price        : ${bitcoin_drop['Close'].iloc[-1]:>12,.2f}
  All-time high       : ${bitcoin_drop['High'].max():>12,.2f}  on {bitcoin_drop['High'].idxmax().date()}
  All-time low        : ${bitcoin_drop['Low'].min():>12,.2f}  on {bitcoin_drop['Low'].idxmin().date()}

  Total return        : +{overall_ret:,.0f}%
  Annualised vol      : {ann_vol:.1f}%

  Green days          : {positive_days:,}  ({positive_days/total_days*100:.1f}%)
  Red days            : {negative_days:,}  ({negative_days/total_days*100:.1f}%)

  Vol ↔ Price move corr : {vol_corr:.4f}  (near zero = volume doesn't predict direction)
""")